data:
  system: "duffing"
  type: "nonautonomous"
  split_ratio: 0.70
  noise_ratio: 25

model:
  fno_flag: True
  kernel_size: 128
  filters: 64
  kernel_size_1: 4
  modes: 200
  input_dim: 1
  lifting_dim: 64
  output_dim: 1
  output_dim_parallel: 1

training:
  batch_size: 5
  pretrain_epochs: 1800
  pretrain_lr: 1e-3
  # network training hyper-parameters
  network_epochs: 500
  network_initial_lr: 1e-3
  network_decay_steps: 100
  network_decay_rate: 0.98
  network_minimum_lr: 5e-4
  # physics training hyper-parameters
  physics_epochs: 1000
  physics_initial_lr: 1e-2
  physics_decay_steps: 100
  physics_decay_rate: 0.96
  physics_minimum_lr: 1e-3
  alternate_number: 0
  lambda_velocity_int: 1.0e-3
  lambda_l1: 2.0e-7

dirs:
  figures: "./figures/"
  results: "./results/"
  checkpoints: "./checkpoints/"
  profiler: "./tboard/profiler/"
  graphs: "./tboard/graphs/"
  training: "./tboard/training/"
  validation: "./tboard/validation/"
  weights: "./tboard/weights/"

hydra:
  run:
    dir: ./outputs/${now:%Y%m%d_%H%M%S}
  sweep:
    dir: ./outputs/${now:%Y%m%d_%H%M%S}
    subdir: running_number_${hydra.job.num}
